sudo: false
language: python
python:
- '3.7'
install:
- pip install pygments lxml setuptools --upgrade
- git clone https://github.com/tabatkins/bikeshed.git
- pip install --editable $PWD/bikeshed
- bikeshed update
script:
- bash "./deploy.sh"
env:
  global:
  - ENCRYPTION_LABEL: "189e52c2c347"
  - COMMIT_AUTHOR_EMAIL: "yoav@yoav.ws"
